// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfwammkjywvzhtvjnqno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpmd2FtbWtqeXd2emh0dmpucW5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDc3NjAsImV4cCI6MjA2NTIyMzc2MH0.4xTpInvbsG-UWmIuENZH-ZT4lunHcuGTM4U4L5FpzI8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);